Add cache

diff --git a/.github/workflows/build_core.yml b/.github/workflows/build_core.yml
--- a/.github/workflows/build_core.yml
+++ b/.github/workflows/build_core.yml
@@ -45,20 +45,62 @@ jobs:
         shell: ${{ contains(inputs.name, 'MinGW') && 'msys2 {0}' || 'bash' }}
 
     steps:
+    - name: Dump Event
+      shell: bash
+      env:
+        EVENT: ${{ toJson(github) }}
+      run: echo "${EVENT}"
+
     - name: Prepare Container
       if: runner.os == 'Linux'
       run: |
         # Containers are lean and may not have packages required by early steps
         elevated() { if [ "$EUID" -ne 0 ]; then sudo "$@"; else "$@"; fi; }
+
         if which apt-get; then
           elevated apt-get -q update
-          elevated apt-get -q install -y curl git sudo tree
+          elevated apt-get -q install -y curl file git gh python3 sudo tree
         fi
+        # fixed dubious ownership issue in a container
+        git config --global --add safe.directory $GITHUB_WORKSPACE
 
     - name: Checkout
       uses: actions/checkout@v6
       with:
         fetch-depth: 0
+
+    - name: Fix Timestamps
+      uses: chetan/git-restore-mtime-action@v2
+
+      # To disable caching, add exceptions to the if statement here
+      # Re-running a workflow will also disable the cache
+    - name: Restore Cache
+      if: github.event_name != 'pull_request'
+      id: cache
+      uses: actions/cache/restore@v5
+      with:
+        path: build
+        key: ${{ github.repository }}/${{ github.ref }}/${{ inputs.name }}/${{ inputs.build_type }}
+
+    - name: Test Cache
+      id: cached
+      shell: bash
+      run: |
+        if [[ "${{ steps.cache.conclusion }}" == "skipped" ]]; then
+          status=skipped
+        elif [[ ${{github.run_attempt}} != 1 ]]; then
+          status=dropped
+        elif [[ -z "${{ steps.cache.outputs.cache-hit }}" ]]; then
+          status=missing
+        else
+          status=okay
+        fi
+        echo "Cache ${status}"
+        echo "status=${status}" >> "$GITHUB_OUTPUT"
+        if [[ "${status}" != "okay" ]]; then
+          echo "Clearing cache"
+          rm -rf build
+        fi
 
     - name: Setup MSVC
       if: runner.os == 'Windows' && !contains(inputs.name, 'MinGW')
@@ -76,7 +118,7 @@ jobs:
         DEPS_COMMAND: ${{ inputs.deps_cmdline }}
         EXTRA_FILES: ${{ inputs.extra_files }}
       run: |
-        mkdir build && cd build
+        mkdir -p build && cd build
 
         attempt() (
           set +e
@@ -98,48 +140,109 @@ jobs:
             wait "$watchdog_pid" 2>&1
 
             [ $exit_code -eq 0 ] && return 0
-            echo "Attempt $i failed. Retrying in ${delay}s" >&2
+            echo "::warning ::Attempt $i failed. Retrying in ${delay}s" >&2
             sleep "${delay}"
             ((delay*=3))
           done
           return 1
         )
 
+        echo ::group::Files
         files=( $EXTRA_FILES )
         for ((i=2;i<=${#files[@]};i+=3)); do
           file="${files[i-2]}"
           hash="${files[i-1]}"
           addr="${files[i]}"
           download="curl -fL '${addr}' | tee '${file}' | sha256sum"
-          verify="echo '${hash} ${file}' | sha256sum -c -"
+          if [[ "${hash}" == '-' ]]; then
+            echo "::warning ::Skipping Checksum for ${file}"
+            verify="true"
+          else
+            verify="echo '${hash} ${file}' | sha256sum -c -"
+            if [ -f "$file" ]; then
+              printf 'found: %s\n' "$(sha256sum "${file}")"
+              if $verify ; then
+                echo Skipping
+                continue
+              else
+                echo Downloading
+                rm "${file}"
+              fi
+            fi
+          fi
           attempt "set -o pipefail; { $download ; } && { $verify ; }"
         done
+        echo ::endgroup::
 
+        echo ::group::Command
         command=( $DEPS_COMMAND )
         command="${command[*]}"
         if [[ -n "$command" ]]; then
           attempt "$command"
         fi
+        echo ::endgroup::
 
-    - name: Configure
-      env:
-        BUILD_TYPE: ${{ inputs.build_type || 'Release' }}
-        BUILD_OPTS: ${{ inputs.build_opts }}
-      run: |
-        git config --global --add safe.directory $GITHUB_WORKSPACE
-        cmake -B build -S . \
-          -DPK3_QUIET_ZIPDIR=ON -G Ninja \
-          -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS
+        echo ::group::List
+        cd ..
+        git status || true
+        find build -ls || true
+        echo ::endgroup::
 
     - name: Build
       id: build
+      env:
+        CACHED: ${{ steps.cached.outputs.status }}
+        BUILD_TYPE: ${{ inputs.build_type }}
+        BUILD_OPTS: ${{ inputs.build_opts }}
       run: |
         export GIT_DESCRIBE="$(git describe --tags --exclude x-*)"
         echo "This will be $GIT_DESCRIBE"
         echo "version=$GIT_DESCRIBE" >> "$GITHUB_OUTPUT"
-        cmake --build build --config ${{ inputs.build_type }}
 
-    - name: Package
+        config () { cmake -B build -S . -DPK3_QUIET_ZIPDIR=ON -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS ; }
+        build () { cmake --build build --config $BUILD_TYPE ; }
+
+        if [[ "$CACHED" == "okay" ]] ; then
+          echo 'Cache hit. Trying quick config'
+          echo ::group::Config
+          if ! config ; then
+            echo ::endgroup::
+            echo '::warning ::Quick config failed. Cleaning up and re-trying'
+            echo ::group::Config
+            rm -rf build/CMakeFiles build/CMakeCache.txt
+            config
+          fi
+          echo ::endgroup::
+        else
+          echo 'Configuring'
+          echo ::group::Config
+          config
+          echo ::endgroup::
+        fi
+
+        if [[ "$CACHED" == "okay" ]] ; then
+          echo 'Cache hit. Trying quick build'
+          echo ::group::Build
+          if ! build ; then
+            echo ::endgroup::
+            echo '::warning ::Quick build failed. Cleaning up and re-trying'
+            echo ::group::Config
+            cmake --build build --target clean
+            rm -rf build/CMakeFiles build/CMakeCache.txt
+            config
+            echo ::endgroup::
+            echo ::group::Build
+            build
+          fi
+          echo ::endgroup::
+        else
+          echo 'Building'
+          echo ::group::Build
+          build
+          echo ::endgroup::
+        fi
+
+    - name: Pre Package
       id: package
       shell: bash
       working-directory: build
@@ -147,7 +250,7 @@ jobs:
         mkdir package
         7z a package/licenses.zip ../docs/licenses/*
 
-        echo "name=${{ runner.os }}-${{ runner.arch }}"-UZDoom-"${{ steps.build.outputs.version }}" >> "$GITHUB_OUTPUT"
+        echo "name=${{ runner.os }}-$(uname -m)-UZDoom-${{ steps.build.outputs.version }}" >> "$GITHUB_OUTPUT"
 
     - name: Package Windows
       if: runner.os == 'Windows'
@@ -163,17 +266,15 @@ jobs:
           unzip -j sndfile.zip libsndfile-1.2.2-win64/bin/sndfile.dll -d package
         fi
 
-        mkdir package/soundfonts
-        cp ../soundfont/uzdoom.sf2 package/soundfonts
+        rm -rf soundfonts fm_banks
 
-        mkdir package/fm_banks
-        cp ../fm_banks/GENMIDI.GS.wopl ../fm_banks/gs-by-papiezak-and-sneakernets.wopn package/fm_banks
+        mkdir -p package/soundfonts
+        cp -f ../soundfont/uzdoom.sf2 package/soundfonts
 
-        if [[ -d ${{ inputs.build_type }} ]]; then
-          mv ${{ inputs.build_type }}/* .
-        fi
+        mkdir -p package/fm_banks
+        cp -f ../fm_banks/GENMIDI.GS.wopl ../fm_banks/gs-by-papiezak-and-sneakernets.wopn package/fm_banks
 
-        cp uzdoom.* *.pk3 package
+        mv -f uzdoom.exe *.pk3 package
 
         cd package
         7z a -sdel -r "${NAME}.zip" *
@@ -211,6 +312,8 @@ jobs:
 
           SIGN_ID="${{ secrets.MACOS_CERTIFICATE_ID }}"
           SIGN_OPTS="--options=runtime"
+        else
+          echo "::warning ::Self-signing application"
         fi
 
         mkdir -p ${app}/Contents/Frameworks
@@ -261,15 +364,43 @@ jobs:
           rm package/licenses.zip
         fi
 
+    - name: List
+      if: always()
+      shell: bash
+      run: |
+        git status || true
+        find build -ls || true
+
     - name: Upload Artifact
       uses: actions/upload-artifact@v7
       with:
         path: build/package
         name: ${{ inputs.name }} ${{ inputs.build_type }}
 
-    - name: List
-      if: always()
+    - name: Prepare Cache
+      if: steps.cached.outputs.status != 'skipped'
       shell: bash
       run: |
-        git status
-        tree -pu build || true
+        # clean up stuff we don't want cached
+        # mainly stuff from packaging steps
+        rm -rf build/AppDir build/package build/*.app
+        sync
+
+      # https://github.com/actions/cache/issues/342
+    - name: Clear Cache
+      if: steps.cached.outputs.status != 'skipped' && steps.cached.outputs.status != 'missing'
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+        REPO: ${{ github.repository }}
+        KEY: ${{ steps.cache.outputs.cache-primary-key }}
+      shell: bash
+      run: |
+        gh api --method DELETE "/repos/${REPO}/actions/caches?key=${KEY// /%20}"
+        sleep 5
+
+    - name: Save Cache
+      if: steps.cached.outputs.status != 'skipped'
+      uses: actions/cache/save@v5
+      with:
+        path: build
+        key: ${{ steps.cache.outputs.cache-primary-key }}
